# Generated by Django 4.1.4 on 2023-02-06 18:37

from django.db import migrations, models
import django.db.models.deletion
import sayt.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=128)),
                ('slug', models.SlugField(blank=True, max_length=128, unique=True)),
                ('is_main', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Category',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waranty', models.CharField(max_length=128)),
                ('collection', models.CharField(max_length=128)),
                ('matras', models.CharField(max_length=128)),
                ('Xususiyatlari', models.CharField(max_length=128)),
                ('qoshimchalari', models.CharField(max_length=128)),
                ('balandligi', models.CharField(max_length=128)),
                ('mehanizm', models.CharField(max_length=128)),
                ('massa', models.CharField(max_length=128)),
                ('Maqsad', models.CharField(max_length=128)),
                ('razmer', models.CharField(max_length=128)),
                ('qattiqlik', models.CharField(max_length=128)),
                ('brand', models.CharField(max_length=128)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=128)),
                ('sale', models.DateTimeField()),
                ('price', models.IntegerField()),
                ('price_true', models.IntegerField(blank=True, null=True)),
                ('credit', models.IntegerField()),
                ('bonus', models.IntegerField()),
                ('size', models.CharField(max_length=122)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tkan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tkan_name', models.CharField(max_length=128)),
                ('tkan_material', models.CharField(max_length=126)),
                ('tkan_price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TkanImg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='Tkan')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sayt.product')),
                ('tkan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sayt.tkan')),
            ],
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('ctg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sayt.category')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='sayt.product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='sub_ctg',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sayt.subcategory'),
        ),
        migrations.CreateModel(
            name='ColorImg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=128, verbose_name=sayt.models.Tkan)),
                ('img', models.ImageField(upload_to='')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sayt.product')),
            ],
        ),
    ]
