# Generated by Django 4.1.6 on 2023-02-09 17:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sayt', '0005_comment_like_dislike'),
    ]

    operations = [
        migrations.AddField(
            model_name='dislike',
            name='user',
            field=models.ManyToManyField(related_name='comment_dislike', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='like',
            name='user',
            field=models.ManyToManyField(related_name='comment_like', to=settings.AUTH_USER_MODEL),
        ),
    ]
