# Generated by Django 4.1.6 on 2023-02-09 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sayt', '0006_dislike_user_like_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dislike',
            name='commentary',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dislike', to='sayt.comment'),
        ),
        migrations.AlterField(
            model_name='like',
            name='commentary',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='like', to='sayt.comment'),
        ),
    ]
