# Generated by Django 4.1.6 on 2023-02-13 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sayt', '0016_remove_product_price_true_remove_product_sale_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='discount',
            name='procent',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
